In [7]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import functions
from google.cloud import bigquery

In [71]:
functions.data_loader()

Uploading raw_apps...
Uploading raw_reviews...
All tables uploaded successfully!

In [8]:
client = bigquery.Client()

query1 = """
SELECT *
FROM `ironhack-497023.google_play_store_apps.raw_reviews`
"""

df_reviews = client.query(query1).to_dataframe()

In [9]:
df_reviews.head()

,app,translated_review,sentiment,sentiment_polarity,sentiment_subjectivity
0,10 Best Foods for You,None,None,NaN,NaN
1,10 Best Foods for You,None,None,NaN,NaN
2,10 Best Foods for You,None,None,NaN,NaN
3,10 Best Foods for You,None,None,NaN,NaN
4,10 Best Foods for You,None,None,NaN,NaN

In [10]:
query2 = """
SELECT *
FROM `ironhack-497023.google_play_store_apps.raw_apps`
"""
df_apps = client.query(query2).to_dataframe()

In [11]:
df_apps.head()

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,B-Grade Renegade,GAME,3.9,24,64M,"1,000+",Paid,$1.99,Teen,Action,"October 17, 2017",0.8.17,3.2 and up
1,Flat Pack,GAME,4.4,862,44M,"100,000+",Free,0,Everyone 10+,Action,"March 16, 2018",1.0.4,7.0 and up
2,Nightenfell: Shared AR,GAME,4.5,20,65M,"1,000+",Paid,$0.99,Everyone 10+,Action,"March 27, 2018",1.0.0,7.0 and up
3,CJ: Strike Back,GAME,4.3,29330,6.9M,"1,000,000+",Free,0,Everyone,Action,"August 17, 2012",1.0.9,2.0.1 and up
4,CS16Client,GAME,4.3,8668,9.1M,"500,000+",Free,0,Teen,Action,"April 1, 2017",1.33,1.5 and up